### ISSUE TITLE
File Form Element don't works

### ISSUE THREAD

**Issue by aight8** [zendframework/zendframework#6212]
I create in a form's init() method a new File Form element and add it to the form itself.

```php
$image = new File('image');
$this->add($image);
```

than i become a fatal error message:

File:
```
......./Zend/InputFilter/Factory.php:156
Message:
Zend\InputFilter\Factory::createInput expects an array or Traversable; received "string"
Stack trace:
#0 ......./Zend/InputFilter/Factory.php(323): Zend\InputFilter\Factory->createInput('image')
#1 ......./Zend/InputFilter/Factory.php(172): Zend\InputFilter\Factory->createInputFilter(Array)
#2 ......./Zend/Form/Form.php(781): Zend\InputFilter\Factory->createInput(Array)
#3 ......./Zend/Form/Form.php(693): Zend\Form\Form->attachInputFilterDefaults(Object(Skill\Form\InputFilter\SkillFilter), Object(Skill\Form\Skill))
#4 ......./Zend/Form/Form.php(204): Zend\Form\Form->getInputFilter()
#5 ......./module/MyModule/view/test/test/test.phtml(10): Zend\Form\Form->prepare()
#6 ......./Zend/View/Renderer/PhpRenderer.php(506): include('/Users/sebi/Sit...')
#7 ......./Zend/View/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#8 ......./Zend/View/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#9 ......./Zend/View/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#10 ......./Zend/Mvc/View/Http/DefaultRenderingStrategy.php(102): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#11 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#12 ......./Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 ......./Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#14 ......./Zend/Mvc/Application.php(352): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#15 ......./Zend/Mvc/Application.php(327): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#16 ......./public/index.php(17): Zend\Mvc\Application->run()
#17 {main}
```

The FIle Element NOT working. Since couple of month.

**Comment by VadimIzmalkov** [comment]
Have the same problem.
When I create form via factory using ServiceManager:
```
$form = $this->getServiceLocator()->get('FormElementManager')->get('ImportContactsForm');
```
I get error
> Zend\InputFilter\Factory::createInput expects an array or Traversable; received "string"

When I create form in the controller:
```
$form = new Form\MailerForm($this->entityManager);
$form->setAttributes([
    'name' => 'import-contacts'
]);
$form->setHydrator(new DoctrineHydrator($this->entityManager));
$form->addUploadFile();
$form->addCitySelect();
$form->addSubmit();
$form->get('submit')->setValue('Save');
```
Everything works fine.

How to fix it?

**Comment by Martin-P** [comment]
> How to fix it?

Please read the entire issue, expecially this comment: https://github.com/zendframework/zf2/issues/6212#issuecomment-46770113

**Comment by VadimIzmalkov** [comment]
I placed 
```
    'di' => [

    ],
```
in application.config.php and still have the issue..

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
