### ISSUE TITLE
Cookies::addCookiesFromResponse Method not returning cookie domains

### ISSUE THREAD

**Issue by jcrawford** [zendframework/zendframework#6616]
I have had this code in place for a while and it was all working fine in the past.  I recently ran the code yesterday and found that it is now throwing some Exceptions.

```
PHP Fatal error:  Uncaught exception 'Zend\Http\Header\Exception\InvalidArgumentException' with message '$cookieDomain is expected to be a cookie domain' in /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Header/SetCookie.php:582
Stack trace:
#0 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Cookies.php(296): Zend\Http\Header\SetCookie::matchCookieDomain('', 'kelbyone.com')
#1 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Cookies.php(180): Zend\Http\Cookies->_matchDomain('kelbyone.com')
#2 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/src/jcrawford/Kelbyone.php(174): Zend\Http\Cookies->getMatchingCookies(Object(Zend\Uri\Http))
#3 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/src/jcrawford/Kelbyone.php(194): jcrawford\Kelbyone->_login()
#4 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/src/jcrawford/Kelbyone.php(67): jcrawford\Kelbyone->_get_playlist('spearsall_trail...')
#5 /Volumes/Storage/Dropbox/Projects/ke in /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Header/SetCookie.php on line 582

Fatal error: Uncaught exception 'Zend\Http\Header\Exception\InvalidArgumentException' with message '$cookieDomain is expected to be a cookie domain' in /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Header/SetCookie.php:582
Stack trace:
#0 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Cookies.php(296): Zend\Http\Header\SetCookie::matchCookieDomain('', 'kelbyone.com')
#1 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Cookies.php(180): Zend\Http\Cookies->_matchDomain('kelbyone.com')
#2 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/src/jcrawford/Kelbyone.php(174): Zend\Http\Cookies->getMatchingCookies(Object(Zend\Uri\Http))
#3 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/src/jcrawford/Kelbyone.php(194): jcrawford\Kelbyone->_login()
#4 /Volumes/Storage/Dropbox/Projects/kelbyone/zf/src/jcrawford/Kelbyone.php(67): jcrawford\Kelbyone->_get_playlist('spearsall_trail...')
#5 /Volumes/Storage/Dropbox/Projects/ke in /Volumes/Storage/Dropbox/Projects/kelbyone/zf/vendor/zendframework/zend-http/Zend/Http/Header/SetCookie.php on line 582
jcrawford@Josephs-Mac-Pro:/Volumes/Storage/Dropbox/Projects/kelbyone/zf # 
```

I have traced this as far as the ```Cookies::addCookiesFromResponse``` method.  When this method makes a call to the following line of code:

```
$cookieHdrs = $response->getHeaders()->get('Set-Cookie');
```

then the following set cookie objects are returned and none of them have the domain set, therefore when it gets to the point where it attempts to match the cookie domain it fails as there is no domain for the cookie so therefore the array index becomes '' rather than 'domain.com'.

Below are the results from the getHeaders call above:

```
ArrayIterator Object
(
    [storage:ArrayIterator:private] => Array
        (
            [0] => Zend\Http\Header\SetCookie Object
                (
                    [name:protected] => vfb_wp_session
                    [value:protected] => ee8a78479f8f0bb964b93705aaf637e4||2818846152||1409411916
                    [version:protected] => 
                    [maxAge:protected] => 
                    [expires:protected] => 2818846152
                    [domain:protected] => 
                    [path:protected] => /
                    [secure:protected] => 
                    [quoteFieldValue:protected] => 
                    [httponly:protected] => 
                    [type] => Cookie
                )

            [1] => Zend\Http\Header\SetCookie Object
                (
                    [name:protected] => vfb_token_set
                    [value:protected] => deleted
                    [version:protected] => 
                    [maxAge:protected] => 
                    [expires:protected] => 1
                    [domain:protected] => 
                    [path:protected] => /
                    [secure:protected] => 
                    [quoteFieldValue:protected] => 
                    [httponly:protected] => 
                    [type] => Cookie
                )

        )

)
```

As you can see there is no domain set in any of these SetCookie objects.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
