### ISSUE TITLE
Error on display config list

### ISSUE THREAD

**Issue by danitome24** [zendframework/zendframework#7706]
Hi all,

I've installed ZFT in my project and I tested all the features of this module. The problem is when I run `zf.php config list` the CLI returns an error like the following:

```
Warning: strpos() expects parameter 1 to be string, object given in /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php on line 150

Call Stack:
    0.0003     222928   1. {main}() /var/www/dtome/guido/vendor/zendframework/zftool/zf.php:0
    0.0635    2279024   2. Zend\Mvc\Application->run() /var/www/dtome/guido/vendor/zendframework/zftool/zf.php:50
    0.0644    2292832   3. Zend\EventManager\EventManager->trigger() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:313
    0.0644    2292832   4. Zend\EventManager\EventManager->triggerListeners() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:207
    0.0644    2294592   5. call_user_func() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
    0.0644    2295160   6. Zend\Mvc\DispatchListener->onDispatch() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
    0.0659    2340232   7. Zend\Mvc\Controller\AbstractController->dispatch() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php:113
    0.0659    2340712   8. Zend\EventManager\EventManager->trigger() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php:116
    0.0659    2340712   9. Zend\EventManager\EventManager->triggerListeners() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:207
    0.0661    2354704  10. call_user_func() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
    0.0661    2354832  11. Zend\Mvc\Controller\AbstractActionController->onDispatch() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
    0.0661    2355184  12. ZFTool\Controller\ConfigController->listAction() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php:83
    0.0700    2440472  13. Zend\Config\Writer\AbstractWriter->toString() /var/www/dtome/guido/vendor/zendframework/zftool/src/ZFTool/Controller/ConfigController.php:42
    0.0700    2440576  14. Zend\Config\Writer\Ini->processConfig() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/AbstractWriter.php:76
    0.0703    2449728  15. Zend\Config\Writer\Ini->addBranch() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php:101
    0.0703    2450912  16. Zend\Config\Writer\Ini->addBranch() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php:125
    0.0704    2457480  17. Zend\Config\Writer\Ini->prepareValue() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php:129
    0.0704    2457584  18. strpos() /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php:150

======================================================================
   The application has thrown an exception!
======================================================================
 Zend\Config\Exception\RuntimeException
 Value can not contain double quotes
----------------------------------------------------------------------
/var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php:153
#0 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php(129): Zend\Config\Writer\Ini->prepareValue(Object(Closure))
#1 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php(125): Zend\Config\Writer\Ini->addBranch(Array, Array)
#2 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/Ini.php(101): Zend\Config\Writer\Ini->addBranch(Array)
#3 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Config/Writer/AbstractWriter.php(76): Zend\Config\Writer\Ini->processConfig(Array)
#4 /var/www/dtome/guido/vendor/zendframework/zftool/src/ZFTool/Controller/ConfigController.php(42): Zend\Config\Writer\AbstractWriter->toString(Array)
#5 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): ZFTool\Controller\ConfigController->listAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/dtome/guido/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/dtome/guido/vendor/zendframework/zftool/zf.php(50): Zend\Mvc\Application->run()
#16 {main}
======================================================================
```

In my `application.config.php` file I have the following:

```
return array(
    'modules' => $modules,
    'module_listener_options' => array(
        'config_glob_paths' => array(
            sprintf('config/autoload/{,*.}{global,%s,local}.php', $env),
        ),
        'module_paths' => array(
            './module',
            './vendor',
        ),
        // Whether or not to enable a configuration cache.
        // If enabled, the merged configuration will be cached and used in
        // subsequent requests.
        'config_cache_enabled' => $enableCache,

        // The key used to create the configuration cache file name.
        'config_cache_key' => 'guido_cache_config',

        // Whether or not to enable a module class map cache.
        // If enabled, creates a module class map cache which will be used
        // by in future requests, to reduce the autoloading process.
        'module_map_cache_enabled' => $enableCache,

        // The key used to create the class map cache file name.
        'module_map_cache_key' => 'module_map',

        // The path in which to cache merged configuration.
        'cache_dir' => __DIR__ . '/../data/cache',

        // Whether or not to enable modules dependency checking.
        // Enabled by default, prevents usage of modules that depend on other modules
        // that weren't loaded.
        'check_dependencies' => !$enableCache,
    ),
);
```

The problem is in `module_listener_options/config_glob_paths` but I don't know how to solve it.

Thanks

**Comment by froschdesign** [comment]
Duplicates zendframework/ZFTool#128

**Comment by froschdesign** [comment]
@danitome24 
Please no cross-posting!
