### ISSUE TITLE
Zend Framework 3.0.0 is not stable

### ISSUE THREAD

**Issue by aight8** [zendframework/zendframework#7735]
Zend Framework 3.0.0 is not stable (composer config mininimum-stability: stable). The error comes from the framework core when I understand it correctly.
Got following error:

```
Fatal error: Uncaught Zend\ModuleManager\Listener\Exception\RuntimeException: Could not find a valid ServiceManager for RoutePluginManager in /var/www/xxx/current/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php:202 Stack trace: #0 /var/www/xxx/current/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent)) #1 /var/www/xxx/current/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent)) #2 /var/www/xxx/current/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(129): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent)) #3 /var/www/xxx/current/vendor/zendframework/zend-mvc/src/Application.php(264): Zend\ModuleManager\ModuleManager->loadModules() #4 /var/www/xxx/current/public/index.php(9): Zend\Mvc\Application::init in /var/www/xxx/current/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php on line 202
```

**Comment by Ocramius** [comment]
This means that the routing module wasn't enabled. How did you install the
framework?

**Comment by aight8** [comment]
It's an already existing application.

I read & migrated followed by this:
https://zendframework.github.io/zend-mvc/migration/to-v3-0/#routing
https://zendframework.github.io/zend-router/migration/v2-to-v3/

What you mean with enabled? I use the zf3 meta package v3.0.0 but "stable" as min. stability. Before I upgrade the min. stability I want to do this on per-component basis.

**Comment by Ocramius** [comment]
You'll need to enable the `Zend\Router` module, basically. Without that
module, there is no router plugin manager.

**Comment by aight8** [comment]
Okey I got that one. Seems to be a small thing but I think it would be nice to write this hint in the migration guide (mvc have a hard dependency on zend-router so you can think it's solved by this).

**Comment by Ocramius** [comment]
If it's not in the migration guide, that's a documentation bug. Are you
able to send a patch, or open an issue on the documentation repo?

**Comment by sebfek** [comment]
I will write issues, there are other components (or better said "Modules" now) which lacks this information.

**Comment by sebfek** [comment]
Migration guide too. It's a additional step migrators have to do to get the working application back.

**Comment by weierophinney** [comment]
This is covered to an extent in the v2-v3 migration guide (https://docs.zendframework.com/tutorials/migration/to-v3/application/). If you follow that, and add the zend-component-installer, as recommended, modules such as zend-router are added to your application configuration for you.

That said, we likely need to cover manual steps as well, as clearly not everyone is doing this. I would recommend doing PRs against that document (it's under the zendframework/tutorials repository).
